evento_app/urls.py
from django.urls import path
from .views import EventoCreateView, EventoDetailView, EventoListView, EventoUpdateView, FormSuccessDeleteView, FormSuccessView, EventoDeleteView
urlpatterns = [
    path('evento_lista', EventoListView.as_view(), name='evento_lista'),
    path('evento_detalhe/<int:pk>', EventoDetailView.as_view(), name='evento_detalhe'),
    path('evento_update/<int:pk>', EventoUpdateView.as_view(), name='evento_atualiza'),
    path('evento_update/evento_success', FormSuccessView.as_view(), name='form_success_update'),
    path('evento_delete/<int:pk>', EventoDeleteView.as_view(), name='evento_delete'),
    path('evento_create', EventoCreateView.as_view(), name='evento_create'),
    path('evento_app/evento_success/<str:tipo_acao>', FormSuccessView.as_view(), name='evento_success'),
    path('evento_app/evento_success', FormSuccessView.as_view(), name='evento_success'),
    path('evento_delete/delete_success', FormSuccessDeleteView.as_view(), name='evento_delete_success'),
]

sol_app/urls.py
from django.urls import path
from .views import FormErrorView, FormSuccessDeleteView, SolDeleteView, SolRecordFormView, FormSuccessView, SolListView, SolDetailView, SolUpdateView
urlpatterns = [
    path('nova_sol', SolRecordFormView.as_view(), name='sol_record_form'),
    path('entry_success', FormSuccessView.as_view(), name='form_success'),
    path('sol_list', SolListView.as_view(), name='sol_list'),
    path('sol_detail/<int:pk>', SolDetailView.as_view(), name='sol_detalhe'),
    path('sol_detail/<str:excluir>/<int:pk>', SolDetailView.as_view(), name='sol_detalhe'),
    path('sol_form/<str:editar>/<int:pk>', SolUpdateView.as_view(), name='sol_form_editar'),
    path('sol_form/editar/entry_success', FormSuccessView.as_view(), name='sol_form_success'),
    path('sol_form_delete/<int:pk>', SolDeleteView.as_view(), name='sol_delete'),
    path('sol_form_delete/delete_success', FormSuccessDeleteView.as_view(), name='delete_success'),
    path('sol_form_delete/error', FormErrorView.as_view(), name='delete_error'),


]

web_project/urls.py
from django.contrib import admin, auth
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path("", include("dashboard_app.urls")),
    path("accounts/profile/", include("dashboard_app.urls")),
    path("cadastros/", include("cadastro_app.urls")),
    path("audita/", include("audit_app.urls")),
    path("solicitacao/", include("sol_app.urls")),
    path("eventos/", include("evento_app.urls")),
    path("usuarios/", include("usuario_app.urls")),
    path("historico/", include("consulta_app.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),
    path("usuarios/cadastro_usuario/login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),


    path("admin/", admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

evento_app/models.py
from django.db import models

from cadastro_app.models import Eventos
from sol_app.models import Solicitacao


class EventoRegistro(models.Model):
    solicitacao = models.ForeignKey(Solicitacao, on_delete=models.PROTECT)
    data_evento = models.DateField()
    tipo_evento = models.ForeignKey(Eventos, on_delete=models.PROTECT)
    descricao = models.TextField(max_length=200)
    documento = models.CharField(max_length=50)
    responsavel = models.CharField(max_length=100, null=True)

evento_app/forms.py
from django import forms
from evento_app.models import EventoRegistro
from sol_app.models import Solicitacao
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Div, Field, Row, Column


class EventoForm(forms.ModelForm):
    class Meta:
        model = EventoRegistro
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(EventoForm, self).__init__(*args, **kwargs)
        self.fields['data_evento'].widget = forms.DateInput(format='%d/%m/%Y', attrs={'placeholder': 'DD/MM/AAAA'})
        self.fields["descricao"].widget.attrs = {"row": 5}
        self.fields["solicitacao"].choices = [
            (item.id, item.nome_referencia) for item in Solicitacao.objects.all()
        ]
        # self.helper = FormHelper(self)
        # self.helper.layout = Layout(
        #     Modal(
        #             # email.help_text was set during the initalization of the django form field
        #             Field('email', placeholder="Email", wrapper_class="mb-0"),
        #             Button(
        #                 "submit",
        #                 "Send Reset Email",
        #                 id="email_reset",
        #                 css_class="btn-primary mt-3",
        #                 onClick="someJavasciptFunction()", # used to submit the form
        #             ),
        #             css_id="my_modal_id",
        #             title="This is my modal",
        #             title_class="w-100 text-center",
        #         )
# )

evento_app/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views import View
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from evento_app.forms import EventoForm
from .models import EventoRegistro, Solicitacao


class EventoCreateView(LoginRequiredMixin, CreateView):
    model = EventoRegistro
    # fields = ['data_evento', 'descricao','documento', 'responsavel', 'tipo_evento','solicitacao']
    form_class = EventoForm
    template_name = 'evento_app/evento_form.html'
    success_url = 'evento_app/evento_success'+'?tipo_acao=criado'

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['solicitacao'].choices = [(item.id, item.nome_referencia) for item in Solicitacao.objects.all()]
        return form
    
    def form_valid(self, form):
        print('Dentro de form_valid')
        response =  super().form_valid(form)
        print('passou no evento')
        solicitacao = form.cleaned_data.get('solicitacao')
        solicitacao_id = solicitacao.id
        print(f'Solicitação ID: {solicitacao_id}')
        
        # Obter o objeto Solicitacao e atualizar o status
        solicitacao = get_object_or_404(Solicitacao, id=solicitacao_id)
        solicitacao.status = "EA"
        solicitacao.save()
        
        return response
    
    def form_invalid(self, form):
        print('Formulário inválido')
        print(form.errors)
        return super().form_invalid(form)
    
    def post(self, request, *args, **kwargs):
        print('Dentro do método post')
        print('Dados do formulário:', request.POST)
        return super().post(request, *args, **kwargs)
    

class EventoListView(LoginRequiredMixin,ListView):
    model = EventoRegistro
    paginate_by = 10
    template_name = 'evento_app/evento_lista.html'


class EventoDetailView(LoginRequiredMixin,DetailView):
    model = EventoRegistro
    template_name = 'evento_app/evento_registro_detalhe.html'


class EventoUpdateView(LoginRequiredMixin,UpdateView):
    model = EventoRegistro
    # fields = ['data_evento', 'descricao','documento', 'responsavel', 'tipo_evento','solicitacao']
    form_class = EventoForm
    template_name = 'evento_app/evento_form.html'
    success_url = 'evento_success' + '?tipo_acao=Alteração'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tipo_acao'] = 'Alterado'
        return context

class FormSuccessView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        print(request.GET)
        acao = request.GET['tipo_acao']
        if acao == 'Alteração':
            return render(request, 'evento_app/modal.html', {'sucesso_enviar': True, 'tipo_acao': 'alterado', 'nome_formulario' : 'Alteração','nome_url': 'evento_lista', 'tipo_cadastro': 'Evento'})
        else:
            return render(request, 'evento_app/modal.html', {'sucesso_enviar': True, 'tipo_acao': 'criado', 'nome_formulario' : 'Criação','nome_url': 'evento_lista','tipo_cadastro': 'Evento'})

class EventoDeleteView(LoginRequiredMixin,DeleteView):
    model = EventoRegistro
    template_name = 'evento_app/evento_delete_form.html'
    success_url = 'delete_success' + '?tipo_acao=deletado'

class FormSuccessDeleteView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        print(request.GET)
        acao = request.GET['tipo_acao']
        if acao == 'deletado':
            return render(request, 'evento_app/modal.html', {'sucesso_enviar': True, 'tipo_acao': 'excluído', 'nome_formulario' : 'Exclusão', 'nome_url':'evento_lista', 'tipo_cadastro': 'Evento'})
        else:
            return render(request, 'evento_app/modal.html', {'sucesso_enviar': True, 'tipo_acao': 'criado', 'nome_formulario' : 'Criação', 'nome_url':'evento_lista', 'tipo_cadastro': 'Evento'})

 

evento_app/templates/evento_app/evento_delete_form.html
{% extends "web_project/base.html" %}
{% block title %}
Apagar?
{% endblock %}
{% block content %}
<div class="container">
<div class="row">
  Apagar registro
</div>
<div class="row mt-3">
   Você quer deletar o registro?
</div>
<div class="row mt-3">
<form method="POST">
    {% csrf_token %}
    <input class="btn" type="submit" value="Apagar registro" />
</form>
</div>
  </div>


<!-- Modal -->


{% endblock %}

evento_app/templates/evento_app/evento_form.html
{% extends "web_project/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Evento
{% endblock %}
{% block content %}
<div class="container-fluid">
<form method="POST">
  <div class="class card mt-3" style="width: 40rem;">
    <div class="card-header">
      <h6 class="card-text text-center">Evento</h6>
    </div>
    <div class="card-body">
      {% csrf_token %}
      {% crispy form %}
    </div>
<div class="text-center mb-2">
  <input class="mt-4"  style="width: 4rem;" type="submit" value="Gravar" />
</div>
  </div>
</form>
<script>
  $(document).ready(function() {
      // Seleciona todos os campos de data renderizados pelo Crispy Forms
      $('#id_data_evento').datepicker({
          dateFormat: 'dd/mm/yy', // Formato de data brasileiro
          changeMonth: true,
          changeYear: true,
          showButtonPanel: true,
          regional: 'pt-BR', // Define o idioma do datepicker para português
          onSelect: function(dateText, inst) {
              $(this).val(dateText); // Quando o usuário seleciona uma data no datepicker
          }
      });

      // Habilita a digitação manual no campo de data
      // Seleciona todos os campos de data renderizados pelo Crispy Forms
      var dateInputs = document.querySelectorAll('#id_data_evento');
      
      // Adiciona um evento de input a cada campo de data
      dateInputs.forEach(function(input) {
          input.addEventListener('input', function() {
              var value = this.value;
              // Verifica se o valor tem 2 ou 5 caracteres e adiciona a barra quando necessário
              if (value.length === 2 || value.length === 5) {
                  this.value += '/';
              }
          });
      });
  });
</script>
</div>

{% endblock %}

evento_app/templates/evento_app/evento_lista.html
{% extends "web_project/base.html" %}
{% block title %}
Lista de Eventos
{% endblock %}
{% block content %}
<style>
    a#eventos {color: aqua;}
</style>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Data Evento</th>
                <th>Descrição</th>
                <th>Documento</th>
                <th>Responsável</th>
                <th>Tipo</th>
                <th>Referência</th>
                <th colspan="3" class="text-center">Ação</th>

            </tr>
        </thead>
        <tbody>
            {% for eventos in object_list %}
            <tr>
                <td><p class="fw-normal">{{eventos.id}}</p></td>
                <td><p class="fw-normal">{{eventos.data_evento|date:"SHORT_DATE_FORMAT" }}</p></td>
                <td><p class="fw-normal">{{eventos.descricao}}</p></td>
                <td><p class="fw-normal">{{eventos.documento}}</p></td>
                <td><p class="fw-normal">{{eventos.responsavel}}</p></td>
                <td><p class="fw-normal">{{eventos.tipo_evento}}</p></td>
                <td><p class="fw-normal">{{eventos.solicitacao.nome_referencia}}</p></td>
                <td> <a href="{% url 'evento_detalhe' eventos.id %}" class="btn btn-outline-primary btn-sm">Exibir</a>
                </td>
                <td> <a href="{% url 'evento_atualiza' eventos.id %}" class="btn btn-outline-primary btn-sm">Editar</a>
                </td>
                <td> <a href="{% url 'evento_delete' eventos.id %}" class="btn btn-outline-danger btn-sm">Excluir</a>
                </td>
            </tr>
            {% empty %}
            <li>Nenhuma Evento ainda. <a href="{% url 'evento_create'%}">Novo Evento</a> </li>
            
            {%endfor%}
        </tbody>
    </table>
    <nav class="Page navigation example">
        <ul class="pagination justify-content-end">
            <li class="page-item">
                {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Anterior</a>
                {% endif %}
            </li>
            {% for page_num in page_obj.paginator.page_range %}
            {% if page_num == page_obj.number %}
            <li class="page-item">
                <a class="active page-link" href="?page={{ page_num }}">{{ page_num }}</a>
            </li>
            {% else %}
            <li class="page-item"> <a class=page-link href="?page={{ page_num }}">{{ page_num }}</a> </li>
            {% endif %}
            {% endfor %}
            </li>
            <li class="page-item">
                {% if page_obj.has_next %}
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Próximo</a>
                {% endif %}
            </li>
        </ul>
    </nav>
    <form action="{% url 'evento_create' %}" method="get">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                 <button class="btn btn-secondary" type="submmit">Novo Evento</button>
            </div>
        </div>
       
{% endblock %}

evento_app/templates/evento_app/evento_registro_detalhe.html
{% extends "web_project/base.html" %}
{% block title %}
Exibir Evento
{% endblock %}
{% block content %}
<span>Data Evento: {{ object.data_evento }}</span><br />
<span>Descrição: {{ object.descricao }}</span>
{% endblock %}

evento_app/templates/evento_app/eventoregistro_form.html
{% extends "web_project/base.html" %}
{% block title %}
Formulário Evento
{% endblock %}
{% block content %}
<p>Evento</p>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Gravar" />
</form>
{% endblock %}

evento_app/templates/evento_app/modal.html
{% extends "web_project/base.html" %}
{% load static %}
{% block title %}
{% endblock %}
{% block content %}
<script src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"> </script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/i18n/jquery-ui-i18n.min.js"></script>
{% if sucesso_enviar %}
  <script type="text/javascript">
    $(document).ready(function(){
      $("#modal").modal('show');
    });
  </script>
{% endif %}
<div class="modal" id="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{{nome_formulario}} de {{tipo_cadastro}}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Registro {{tipo_acao}} com sucesso.</p>
      </div>
      <div class="modal-footer">
        <a href="{%url nome_url %}" type="button" class="btn btn-secondary">Fechar</a>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>
{% endblock %}