sol_app/urls.py
from django.urls import path
from .views import FormErrorView, FormSuccessDeleteView, SolDeleteView, SolRecordFormView, FormSuccessView, SolListView, SolDetailView, SolUpdateView
urlpatterns = [
    path('nova_sol', SolRecordFormView.as_view(), name='sol_record_form'),
    path('entry_success', FormSuccessView.as_view(), name='form_success'),
    path('sol_list', SolListView.as_view(), name='sol_list'),
    path('sol_detail/<int:pk>', SolDetailView.as_view(), name='sol_detalhe'),
    path('sol_detail/<str:excluir>/<int:pk>', SolDetailView.as_view(), name='sol_detalhe'),
    path('sol_form/<str:editar>/<int:pk>', SolUpdateView.as_view(), name='sol_form_editar'),
    path('sol_form/editar/entry_success', FormSuccessView.as_view(), name='sol_form_success'),
    path('sol_form_delete/<int:pk>', SolDeleteView.as_view(), name='sol_delete'),
    path('sol_form_delete/delete_success', FormSuccessDeleteView.as_view(), name='delete_success'),
    path('sol_form_delete/error', FormErrorView.as_view(), name='delete_error'),


]

web_project/urls.py
from django.contrib import admin, auth
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path("", include("dashboard_app.urls")),
    path("accounts/profile/", include("dashboard_app.urls")),
    path("cadastros/", include("cadastro_app.urls")),
    path("audita/", include("audit_app.urls")),
    path("solicitacao/", include("sol_app.urls")),
    path("eventos/", include("evento_app.urls")),
    path("usuarios/", include("usuario_app.urls")),
    path("historico/", include("consulta_app.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),
    path("usuarios/cadastro_usuario/login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),


    path("admin/", admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sol_app/models.py
from django.db import models
from cadastro_app.models import Funcionarios, Regioes, Setores, TiposOS
from django.utils import timezone


class Solicitacao(models.Model):
    ABERTA = 'AB'
    EM_ANDAMENTO = 'EA'
    FINALIZADA = 'FI'
    CANCELADA = 'CA'

    STATUS_CHOICES = [
        (ABERTA, 'Aberta'),
        (EM_ANDAMENTO, 'Em andamento'),
        (FINALIZADA, 'Finalizada'),
        (CANCELADA, 'Cancelada'),
    ]
    nome_referencia = models.CharField(max_length=200, verbose_name='Referência',)
    nome_reduzido = models.CharField(max_length=50)
    doc_sol = models.CharField(max_length=100, verbose_name='Documento da Solicitação')
    data_sol = models.DateField(verbose_name='Data da Solicitação')
    endereco = models.CharField(max_length=50)
    bairro = models.CharField(max_length=50)
    regiao = models.ForeignKey(Regioes, on_delete=models.PROTECT)
    setor = models.ForeignKey(Setores, on_delete=models.PROTECT)
    responsavel = models.ForeignKey(Funcionarios, on_delete=models.PROTECT, related_name='funcionario_responsavel')
    contato = models.ForeignKey(Funcionarios, on_delete=models.PROTECT, related_name='funcionario_contato')
    tipoos = models.ForeignKey(TiposOS, on_delete=models.PROTECT)
    equipe_dpo = models.ManyToManyField(Funcionarios, through="SolicitacaoFuncionarios")
    nome_equipe = models.CharField(max_length=50, blank=True, null=True)
    data_criacao = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default=ABERTA, blank=True, null=True)


    def save(self, *args, **kwargs):
        #self.status = 'AB'
        super().save(*args, **kwargs)
        if not self.nome_equipe:
            ano_atual = timezone.now().year
            self.nome_equipe = f'EQP_{self.id}_{ano_atual}'
            print('aqui está')
            self.save(update_fields=['nome_equipe'])
        


class SolicitacaoFuncionarios(models.Model):
    class EquipeFormacaoRegra(models.TextChoices): 
        CHEFE = "CHEFE", "Chefe"
        MEMBRO = "MEMBRO", "Membro" 
    solicitacao = models.ForeignKey(Solicitacao, on_delete=models.CASCADE) 
    funcionario = models.ForeignKey(Funcionarios, on_delete=models.CASCADE)
    funcao = models.CharField(verbose_name="Posição na equipe", choices=EquipeFormacaoRegra.choices, max_length=20)

sol_app/forms.py
from django import forms
from .models import Solicitacao
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Div, Field, Row, Column


class SolForm(forms.ModelForm):
    class Meta:
        model = Solicitacao
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(SolForm, self).__init__(*args, **kwargs)
        self.fields['status'].initial = 'AB'  # Defina o valor padrão aqui
        self.fields['status'].widget = forms.HiddenInput()
        self.fields['nome_equipe'].widget = forms.HiddenInput()
        self.fields['data_sol'].widget = forms.DateInput(format='%d/%m/%Y', attrs={'placeholder': 'DD/MM/AAAA'})
        self.helper = FormHelper(self)
        print('form')
        self.helper.layout = Layout(
            Row(
                Column('nome_referencia', css_class='col-md-4'),
                Column('nome_reduzido', css_class='col-md-4'),
            ),
            Row(
                Column('doc_sol', css_class='col-md-4'),
                Column('data_sol', css_class='col-md-4'),
            ),
            Row(
                Column('endereco', css_class='col-md-4'),
                Column('bairro', css_class='col-md-4'),
                Column('regiao', css_class='col-md-4'),
            ),
            Row(
                Column('setor', css_class='col-md-4'),
                Column('responsavel', css_class='col-md-4'),
                Column('contato', css_class='col-md-4'),
            ),
            Row(
                Column('tipoos', css_class='col-md-4'),
                Column('equipe_dpo', css_class='col-md-4'),
                # Column('nome_equipe', css_class='col-md-4'),
            ),
            # Row(
            #     Column('status', css_class='col-md-4'),
               
            # ),
        )

sol_app/views.py
from typing import Any
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.edit import FormView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic import DetailView
from django.views import View
from django.utils import timezone
from sol_app.models import Solicitacao
from .forms import SolForm
from django.db.models import ProtectedError
from django.contrib.auth.mixins import LoginRequiredMixin


class SolRecordFormView(LoginRequiredMixin, FormView):
    template_name = "sol_app/sol_form.html"
    form_class = SolForm
    success_url = "entry_success" + '?tipo_acao=criado'
    
    def get_context_data(self, **kwargs) -> dict[str, Any]:
        print('haqui')
        
        context = super().get_context_data(**kwargs)
        context["tipo_solicitacao"] = 'Nova '
        context['tipo_acao'] = 'Criado'
        return context

    def form_valid(self, form):
        print('aqui')
        form.save()
        return super().form_valid(form)
    
    
    def form_invalid(self, form):
        print('O formulário é inválido!')
        print(form.errors)  # Imprime os erros de validação
        return super().form_invalid(form)
    

class FormSuccessView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        acao = request.GET['tipo_acao']
        print(acao)
        if acao == 'Alteração':
            return render(request, 'evento_app/modal.html', {'sucesso_enviar': True, 'tipo_acao': 'alterado', 'nome_formulario' : 'Alteração','nome_url': 'sol_list', 'tipo_cadastro': 'Solicitação'})
        else:
            return render(request, 'evento_app/modal.html', {'sucesso_enviar': True, 'tipo_acao': 'criado', 'nome_formulario' : 'Criação','nome_url': 'sol_list','tipo_cadastro': 'Solicitação'})


class SolListView(LoginRequiredMixin, ListView):
    model = Solicitacao
    paginate_by = 10
    template_name = "sol_app/sol_lista.html"
    ordering = ['-id']

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["agora"] = timezone.now()
        return context


class SolDetailView(LoginRequiredMixin, DetailView):
    model = Solicitacao
    template_name = "sol_app/sol_detail.html"


class SolUpdateView(LoginRequiredMixin, UpdateView):
    model = Solicitacao
    form_class = SolForm
    template_name = "sol_app/sol_form.html"
    success_url = "entry_success" + '?tipo_acao=Alteração'
    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['tipo_acao'] = 'Alterado'
        context["tipo_solicitacao"] = 'Atualização de '
        return context
    


class SolDeleteView(LoginRequiredMixin, DeleteView):
    model = Solicitacao
    template_name = "sol_app/sol_delete_form.html"
    success_url = "delete_success" + '?tipo_acao=deletado'
    error_url = reverse_lazy("delete_error")

    def dispatch(self, request, *args, **kwargs):
        try:
            return super().dispatch(request, *args, **kwargs)
        except ProtectedError as e:
            print(e)
            return HttpResponseRedirect(self.error_url)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['info_error'] = 'Tem eventos'
        return context


class FormErrorView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        msg = "Solicitação não pode ser excluída, pois há eventos registrados no histórico dela."
        return render(
            request, "sol_app/msg_erro_excluir.html", context={"info_error": msg}
        )
    

class FormSuccessDeleteView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        print(request.GET)
        acao = request.GET['tipo_acao']
        if acao == 'deletado':
            return render(request, 'evento_app/modal.html', {'sucesso_enviar': True, 'tipo_acao': 'excluído', 'nome_formulario' : 'Exclusão', 'nome_url':'sol_list', 'tipo_cadastro': 'Solicitação'})
        else:
            return render(request, 'evento_app/modal.html', {'sucesso_enviar': True, 'tipo_acao': 'criado', 'nome_formulario' : 'Criação', 'nome_url':'sol_list', 'tipo_cadastro': 'solicitação'})

sol_app/templates/sol_app/msg_erro_excluir.html
{% extends "web_project/base.html" %}
{% block title %}
{% endblock %}
{% block content %}
{% if info_error %}
  <script type="text/javascript">
    $(document).ready(function(){
      $("#modal").modal('show');
    });
  </script>
{% endif %}

<div class="modal" id="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-danger">Aviso</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>{{info_error}}</p>
      </div>
      <div class="modal-footer">
        <a href="{%url 'sol_list'%}" type="button" class="btn btn-secondary" >Close</a>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>
{{info_error}}
{% endblock %}

sol_app/templates/sol_app/sol_delete_form.html
{% extends "web_project/base.html" %}
{% block title %}
Apagar Registro
{% endblock %}
{% block content %}
<div class="row text-center">
  <div class="card border-dark mb-3 mt-5" style="width: 18rem;margin: 0 auto; float: none;">
    <div class="card-body">
      <h5 class="card-title">Apagar Solicitação</h5>
      <p class="card-text">Você quer deletar essa solicitação?</p>
      <form method="POST">
        {% csrf_token %}
          <button class="btn btn-secondary" type="submit" value="Apagar"  > Apagar </button>
          <a class="btn btn-secondary"  href="{% url 'sol_list' %}">Cancelar</a>
      </form>
    </div>
  </div>
</div>
{% endblock %}

sol_app/templates/sol_app/sol_detail.html
{% extends "web_project/base.html" %}
{% block title %}
Detalhe
{% endblock %}
{% block content %}

<div class="row  pt-5">
  <div class="row">
    <div class="col-4">
      <dt class="col"> Nome de Referência</dt>
      <span>
        <dd class="col">{{solicitacao.nome_referencia}}</dd>
      </span>
    </div>
    <div class="col-4">
      <dt class="col"> Nome Reduzido:</dt>
      <span>
        <dd class="col">{{solicitacao.nome_reduzido}}</dd>
      </span>
    </div>
  </div>
  <div class="row">
    <div class="col-4">
      <dt class="col"> Documento da Solicitação</dt>
      <span>
        <dd class="col">{{solicitacao.doc_sol}}</dd>
      </span>
    </div>
    <div class="col-4">
      <dt> Data da Solicitação:</dt>
      <span>
        <dd> {{solicitacao.data_sol}}</dd>
      </span>
    </div>
  </div>
  <div class="row">
    <div class="col-4">
      <dt class="col"> Endereço: </dt>
      <span>
        <dd class="col">{{solicitacao.endereco}}</dd>
      </span>
    </div>
    <div class="col-4">
      <dt class="col"> Bairro:</dt>
      <span>
        <dd class="col">{{solicitacao.bairro}}</dd>
      </span>
    </div>
    <div class="col-4">
      <dt class="col"> Região: </dt>
      <span>
        <dd class="col"> {{solicitacao.regiao}}</dd>
      </span>
    </div>
  </div>
  <div class="row">
    <div class="col-4">
      <dt class="col"> Setor: </dt>
      <span>
        <dd class="col"> {{solicitacao.setor}}</dd>
      </span>
    </div>
    <div class="col-4">
      <dt class="col"> Resp. pela Solicitação: </dt>
      <span>
        <dd class="col"> {{solicitacao.responsavel}}</dd>
      </span>
    </div>
    <div class="col-4">
      <dt class="col"> Contato: </dt>
      <span>
        <dd class="col"> {{solicitacao.contato}}</dd>
      </span>
    </div>
    </div>
    <div class="row">
      <div class="col-4">
        <dt class="col"> Tipo de Obra/Serviço</dt>
        <span>
          <dd class="col">{{solicitacao.tipoos}}</dd>
        </span>
      </div>
      <div class="col-4">
        <dt class="col">Equipe DPO</dt>
        <span>
          <dd class="col">{{solicitacao.nome_equipe}}</dd>
        </span>
      </div>
      <div class="col-4">
        <dt class="col">Status</dt>
        <span>
          <dd class="col">{{solicitacao.get_status_display}}</dd>
        </span>
      </div>
    </div>
<div class="row text-center mt-5">
  <div class="col">
    <a href="{% url 'sol_list'%}" class="card-link">Voltar</a>
  </div>
</div>

  
  </div>
</div>


{% endblock %}

sol_app/templates/sol_app/sol_form.html
{% extends "web_project/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Solicitação
{% endblock %}
{% block content %}
<h5 class="pt-5 text-center pb-3">{{tipo_solicitacao}} Solicitação</h5>
<form method="POST">
  <div class="class card">
    <div class="card-header">
      <h6 class="card-text">Solicitação</h6>
    </div>
    <div class="card-body">
      {% csrf_token %}
      {% crispy form %}
    </div>
  
<div class="row">
      <div class="col-12 text-center mt-3 mb-3">
             <input class="btn btn-secondary" type="submit" value="Gravar" />
      </div>
    </div> 
  </div>
</form>
<script>
  $(document).ready(function () {
    // Seleciona todos os campos de data renderizados pelo Crispy Forms
    $('#id_data_sol').datepicker({
      dateFormat: 'dd/mm/yy', // Formato de data brasileiro
      changeMonth: true,
      changeYear: true,
      showButtonPanel: true,
      regional: 'pt-BR', // Define o idioma do datepicker para português
      onSelect: function (dateText, inst) {
        $(this).val(dateText); // Quando o usuário seleciona uma data no datepicker
      }
    });

    // Habilita a digitação manual no campo de data
    // Seleciona todos os campos de data renderizados pelo Crispy Forms
    var dateInputs = document.querySelectorAll('#id_data_sol');

    // Adiciona um evento de input a cada campo de data
    dateInputs.forEach(function (input) {
      input.addEventListener('input', function () {
        var value = this.value;
        // Verifica se o valor tem 2 ou 5 caracteres e adiciona a barra quando necessário
        if (value.length === 2 || value.length === 5) {
          this.value += '/';
        }
      });
    });
  });
</script>
{% endblock %}

sol_app/templates/sol_app/sol_lista.html
{% extends "web_project/base.html" %}
{% block title %}
Lista de Solicitações
{% endblock %}
{% block content %}
<style>
    a#solicita {color: aqua;}
</style>

    {% if object_list %}
    <table role="table" class="table table-striped">
        <thead>
            <tr>
                <th>Tipo</th>
                <th>Referência</th>
                <th>Documento</th>
                <th>Data</th>
                <th>Região</th>
                <th>Setor</th>
                <th>Equipe</th>
                <th colspan="3" class="text-center">Ação</th>
            </tr>
        </thead>
        <tbody>
            {%endif%}
            {% for solicitacao in object_list %}
            <tr>
                <td><p class="fw-normal">{{solicitacao.tipoos}}</p></td>
                <td><p class="fw-normal">{{solicitacao.nome_referencia}}</p></td>
                <td><p class="fw-normal">{{solicitacao.doc_sol}}</p></td>
                <td><p class="fw-normal">{{solicitacao.data_sol |date:"SHORT_DATE_FORMAT" }}</td>
                <td><p class="fw-normal">{{solicitacao.regiao}}</p></td>
                <td><p class="fw-normal">{{solicitacao.setor}}</p></td>
                <td><p class="fw-normal">{{solicitacao.nome_equipe}}</p></td>
                <td> <a href="{% url 'sol_detalhe' solicitacao.id %}" class="btn btn-outline-primary btn-sm">Exibir</a>
                </td>
                <td> <a href="{% url 'sol_form_editar' 'editar' solicitacao.id %}"
                        class="btn btn-outline-primary btn-sm">Editar</a>
                </td>
                <td> <a href="{% url 'sol_delete' solicitacao.id %}" class="btn btn-outline-danger btn-sm">Excluir</a>
                </td>
            </tr>
            {% empty %}
            <div class="mb-3 mt-3">
                Nenhuma Solicitação ainda.
            </div>
            <div>
                <a class="btn btn-secondary" href="{% url 'sol_record_form'%}">Nova Solicitação</a> </li>
            </div>
            </div>
            {%endfor%}
        </tbody>
    </table>
    {% if object_list %}
    <div role="navigation" class="row">
        <nav class="Page navigation example">
            <ul class="pagination justify-content-end">
                <li class="page-item">
                    {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Anterior</a>
                    {% endif %}
                </li>
                {% for page_num in page_obj.paginator.page_range %}
                {% if page_num == page_obj.number %}
                <li class="page-item">
                    <a class="active page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item"> <a class=page-link href="?page={{ page_num }}">{{ page_num }}</a> </li>
                {% endif %}
                {% endfor %}
                </li>
                <li class="page-item">
                    {% if page_obj.has_next %}
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Próximo</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
    {%endif%}
    {% if object_list %}
    <form action="{% url 'sol_record_form' %}" method="get">
        {% csrf_token %}
        <div role="contentinfo" class="row">
            <div class="col-6">
                 <button type="submit" class="btn btn-secondary mt-3">Nova Solicitação</button>
            </div>
           
        </div>
    </form>
    {%endif%}
</ul>
{% endblock %}